name: LilyPad-PortalCommand
version: ${build.number}
description: LilyPad

author: LilyPad
website: http://www.lilypadmc.org/

main: ${main.class}
depend: [LilyPad-Connect, LilyPad-Portal]

commands:
  server:
    description:
    usage:
